import { html } from 'htm/preact';
import {
    LayoutDashboard,
    Users,
    Router,
    Calendar,
    FileText,
    Warehouse,
    Settings,
    ClipboardList,
    View,
    History,
    ShieldCheck,
    UserCog,
    ChevronDown,
    Menu,
    Pencil,
    Trash2,
    ChevronLeft,
    ChevronRight,
    List,
    Undo2,
    Search,
    X,
    MapPin,
    ArrowRight,
    ArrowRightLeft,
    FileUp,
    FileDown,
    Info,
    LocateFixed,
    Pin,
    PinOff,
    GitFork,
    Map,
    Wrench,
    Coins,
    FileCog,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    SortAsc,
    SortDesc,
    ArrowUpDown,
    Filter,
    Printer,
    Network,
    Tags,
    Copy,
    Lock,
} from 'lucide-preact';

export const icons = {
  dashboard: html`<${LayoutDashboard} />`,
  customers: html`<${Users} />`,
  devices: html`<${Router} />`,
  planning: html`<${Calendar} />`,
  invoicing: html`<${FileText} />`,
  warehouse: html`<${Warehouse} />`,
  settings: html`<${Settings} />`,
  tools: html`<${Wrench} />`,
  coins: html`<${Coins} />`,
  audit: html`<${ClipboardList} />`,
  columns: html`<${View} />`,
  history: html`<${History} />`,
  logo: html`<${ShieldCheck} />`,
  userManagement: html`<${UserCog} />`,
  list: html`<${List} />`,
  chevron: html`<${ChevronDown} />`,
  menu: html`<${Menu} />`,
  edit: html`<${Pencil} />`,
  delete: html`<${Trash2} />`,
  restore: html`<${Undo2} />`,
  chevronLeft: html`<${ChevronLeft} />`,
  chevronRight: html`<${ChevronRight} />`,
  search: html`<${Search} />`,
  close: html`<${X} />`,
  mapPin: html`<${MapPin} />`,
  arrowRight: html`<${ArrowRight} />`,
  importExport: html`<${ArrowRightLeft} />`,
  upload: html`<${FileUp} />`,
  download: html`<${FileDown} />`,
  info: html`<${Info} />`,
  locate: html`<${LocateFixed} />`,
  pin: html`<${Pin} />`,
  pinOff: html`<${PinOff} />`,
  tree: html`<${GitFork} />`,
  map: html`<${Map} />`,
  deviceTemplates: html`<${FileCog} />`,
  toastSuccess: html`<${CheckCircle2} />`,
  toastError: html`<${XCircle} />`,
  toastWarning: html`<${AlertTriangle} />`,
  toastInfo: html`<${Info} />`,
  sortAsc: html`<${SortAsc} />`,
  sortDesc: html`<${SortDesc} />`,
  sort: html`<${ArrowUpDown} />`,
  filter: html`<${Filter} />`,
  print: html`<${Printer} />`,
  ipam: html`<${Network} />`,
  tags: html`<${Tags} />`,
  copy: html`<${Copy} />`,
  vpn: html`<${Lock} />`,
};